spring:
  data:
    mongodb:
      username: app-user
      password: app-user
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
